# Generated by Django 3.0.4 on 2020-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='ecart',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
