# Generated by Django 3.0.4 on 2020-07-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
